apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buy-go
  template:
    metadata:
      labels:
        app: buy-go
    spec:
      containers:
      - name: buy-go
        image: buy-go:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: buy-go
spec:
  type: LoadBalancer
  selector:
    app: buy-go
  ports:
    - port: 8081
      targetPort: 8081
