apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-reader-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-reader-django
  template:
    metadata:
      labels:
        app: order-reader-django
    spec:
      containers:
      - name: order-reader-django
        image: order-reader-django:latest
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: order-reader-django
spec:
  type: LoadBalancer
  selector:
    app: order-reader-django
  ports:
    - port: 8001
      targetPort: 8001
