
# Use the official Python image as a base image
#FROM python:3.8
FROM python:3.8-alpine
RUN apk add --update alpine-sdk

# Set the working directory in the container
WORKDIR /app

#RUN pip install --only-binary :all: greenlet
#RUN pip install --only-binary :all: Flask-SQLAlchemy

# Copy and install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port your Flask app will run on
EXPOSE 8000

# Define the command to run your Flask application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

