# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get install -y wget && \
    wget -qO - https://packages.confluent.io/deb/6.2/archive.key | apt-key add - && \
    echo "deb [arch=amd64] https://packages.confluent.io/deb/6.2 stable main" >> /etc/apt/sources.list.d/confluent.list && \
    apt-get update && \
    apt-get install -y librdkafka-dev && \
    pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]
