# Use the official Go image as a base image
FROM golang:1.18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the Go application source code into the container
COPY . .

# Build the Go application
RUN go build -o main

# Expose a port (if your application listens on a specific port)
# EXPOSE 8080
EXPOSE 8080


# Define the command to run your Go application
CMD ["./main"]


