# Generated by Django 4.2.6 on 2023-10-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
        ),
    ]
