# Generated by Django 4.2.6 on 2023-10-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reader', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['productName'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pstatus'], name='pstatus_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['quantity'], name='quantity_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['price'], name='price_idx'),
        ),
    ]
